// Capsule Wardrobe Data v1
// To change password: echo -n 'newpassword' | shasum -a 256
const PASSWORD_HASH = '72fa89b0563dde8843e7a7b3eed39bbe007a280b39e3784d8d16f253b888e7ea';

const WARDROBE = {
  palette: {
    neutrals: ['navy', 'olive', 'charcoal', 'tan'],
    leather: ['brown', 'chestnut'],
    accents: ['rust', 'burgundy'],
    maxColorsPerOutfit: 3
  },

  colorHex: {
    navy: '#2c3e50',
    olive: '#556b2f',
    charcoal: '#36454f',
    tan: '#d2b48c',
    chestnut: '#954535',
    brown: '#5c4033',
    rust: '#b7410e',
    burgundy: '#800020',
    white: '#f0efe9',
    black: '#1a1a1a',
    gray: '#808080',
    'forest green': '#228b22',
    'light blue': '#a4c8e1',
    'dark olive': '#556b2f',
    'dark brown': '#5c4033',
    sage: '#87ae73',
    chambray: '#5b7fa6',
    khaki: '#c3b091',
    magnet: '#4a4a4a'
  },

  items: [
    // === FOOTWEAR ===
    {
      id: 'rm-williams',
      name: 'RM Williams Craftsman',
      category: 'footwear',
      subcategory: 'boots',
      role: 'Dress / smart-casual boot',
      colors: ['chestnut'],
      quantity: 1,
      status: 'to-buy',
      priority: 'spring',
      seasons: ['spring', 'summer', 'fall'],
      formality: 'smart-casual',
      tags: ['leather', 'dress', 'travel', 'town'],
      pairsWithIds: ['chinos-khaki', 'chinos-olive', 'ocbd-white', 'ocbd-blue', 'ocbd-chambray'],
      conflicts: ['vidda-pro-1', 'vidda-pro-2'],
      situations: ['dinner', 'travel', 'events'],
      image: 'img/wardrobe/rm-williams.jpg',
      washAfterWears: null
    },
    {
      id: 'grant-stone',
      name: 'Grant Stone Diesel',
      category: 'footwear',
      subcategory: 'boots',
      role: 'Everyday boot',
      colors: ['dark brown'],
      quantity: 1,
      status: 'to-buy',
      priority: 'spring',
      seasons: ['spring', 'fall', 'winter'],
      formality: 'casual',
      tags: ['leather', 'everyday', 'town'],
      pairsWithIds: ['outlier-charcoal', 'outlier-navy', 'ocbd-white', 'ocbd-blue', 'ocbd-chambray'],
      conflicts: [],
      situations: ['daily wear', 'town', 'casual meetings'],
      image: 'img/wardrobe/grant-stone.jpg',
      washAfterWears: null
    },
    {
      id: 'red-wing',
      name: 'Red Wing Moc Toe',
      category: 'footwear',
      subcategory: 'boots',
      role: 'Work boot',
      colors: ['brown'],
      quantity: 1,
      status: 'to-buy',
      priority: null,
      seasons: ['spring', 'fall', 'winter'],
      formality: 'rugged',
      tags: ['leather', 'work', 'outdoor', 'rugged'],
      pairsWithIds: ['vidda-pro-1', 'vidda-pro-2', 'filson-flannel', 'filson-guide-1', 'filson-guide-2'],
      conflicts: ['chinos-khaki', 'chinos-olive'],
      situations: ['outdoor projects', 'rough use'],
      image: 'img/wardrobe/red-wing.webp',
      washAfterWears: null
    },
    {
      id: 'schnees',
      name: 'Schnees Beartooth',
      category: 'footwear',
      subcategory: 'boots',
      role: 'Extreme winter boot',
      colors: ['brown'],
      quantity: 1,
      status: 'to-buy',
      priority: null,
      seasons: ['winter'],
      formality: 'rugged',
      tags: ['winter', 'outdoor', 'rugged', 'snow'],
      pairsWithIds: ['vidda-pro-1', 'vidda-pro-2', 'mackinaw'],
      conflicts: ['chinos-khaki', 'chinos-olive', 'polo-navy', 'polo-sage'],
      situations: ['Ely winter', 'snow', 'cold'],
      image: 'img/wardrobe/schnees.jpg',
      washAfterWears: null
    },
    {
      id: 'muck-boot',
      name: 'Muck Boot',
      category: 'footwear',
      subcategory: 'boots',
      role: 'Mud / wet conditions',
      colors: ['black'],
      quantity: 1,
      status: 'owned',
      priority: null,
      seasons: ['spring', 'fall'],
      formality: 'rugged',
      tags: ['outdoor', 'rugged', 'wet'],
      pairsWithIds: ['vidda-pro-1', 'vidda-pro-2'],
      conflicts: ['chinos-khaki', 'chinos-olive', 'ocbd-white'],
      situations: ['yard work', 'rain', 'shoulder seasons'],
      image: 'img/wardrobe/muck-boot.jpg',
      washAfterWears: null
    },
    {
      id: 'salomon-hiking',
      name: 'Salomon X Ultra GTX',
      category: 'footwear',
      subcategory: 'shoes',
      role: 'Hiking shoe',
      colors: ['magnet'],
      quantity: 1,
      status: 'owned',
      priority: null,
      seasons: ['spring', 'summer', 'fall'],
      formality: 'rugged',
      tags: ['outdoor', 'hiking', 'trail'],
      pairsWithIds: ['vidda-pro-1', 'vidda-pro-2', 'merino-gray', 'merino-navy', 'merino-rust'],
      conflicts: ['chinos-khaki', 'chinos-olive'],
      situations: ['BWCA', 'North Shore', 'trails'],
      image: 'img/wardrobe/salomon-hiking.jpg',
      washAfterWears: null
    },
    {
      id: 'koio',
      name: 'Koio Capri',
      category: 'footwear',
      subcategory: 'shoes',
      role: 'Summer casual sneaker',
      colors: ['white'],
      quantity: 1,
      status: 'to-buy',
      priority: 'summer',
      seasons: ['spring', 'summer'],
      formality: 'casual',
      tags: ['casual', 'travel', 'town', 'summer'],
      pairsWithIds: ['outlier-charcoal', 'outlier-navy', 'polo-navy', 'polo-sage'],
      conflicts: ['vidda-pro-1', 'vidda-pro-2', 'filson-guide-1', 'filson-guide-2'],
      situations: ['travel', 'town', 'warm weather'],
      image: 'img/wardrobe/koio.jpg',
      washAfterWears: null
    },
    {
      id: 'rancourt',
      name: 'Rancourt Ranger Moc',
      category: 'footwear',
      subcategory: 'shoes',
      role: 'Camp / relaxed shoe',
      colors: ['brown'],
      quantity: 1,
      status: 'to-buy',
      priority: 'summer',
      seasons: ['summer'],
      formality: 'casual',
      tags: ['casual', 'relaxed', 'summer', 'lake'],
      pairsWithIds: ['outlier-charcoal', 'outlier-navy', 'merino-gray', 'merino-navy'],
      conflicts: ['filson-guide-1', 'filson-guide-2', 'mackinaw'],
      situations: ['lake', 'summer evenings'],
      image: 'img/wardrobe/rancourt.jpg',
      washAfterWears: null
    },

    // === PANTS ===
    {
      id: 'vidda-pro-1',
      name: 'Fjallraven Vidda Pro',
      category: 'pants',
      subcategory: 'outdoor',
      role: 'Rugged outdoor pant',
      colors: ['dark olive'],
      quantity: 1,
      status: 'to-buy',
      priority: 'spring',
      seasons: ['spring', 'summer', 'fall', 'winter'],
      formality: 'rugged',
      tags: ['outdoor', 'rugged', 'hiking', 'work'],
      pairsWithIds: ['red-wing', 'salomon-hiking', 'schnees', 'muck-boot', 'filson-guide-1', 'filson-guide-2', 'filson-flannel', 'mackinaw'],
      conflicts: ['rm-williams', 'koio'],
      situations: ['outdoor work', 'hiking', 'winter'],
      image: 'img/wardrobe/vidda-pro-1.jpg',
      washAfterWears: 7
    },
    {
      id: 'vidda-pro-2',
      name: 'Fjallraven Vidda Pro',
      category: 'pants',
      subcategory: 'outdoor',
      role: 'Rugged outdoor pant',
      colors: ['dark olive'],
      quantity: 1,
      status: 'to-buy',
      priority: 'spring',
      seasons: ['spring', 'summer', 'fall', 'winter'],
      formality: 'rugged',
      tags: ['outdoor', 'rugged', 'hiking', 'work'],
      pairsWithIds: ['red-wing', 'salomon-hiking', 'schnees', 'muck-boot', 'filson-guide-1', 'filson-guide-2', 'filson-flannel', 'mackinaw'],
      conflicts: ['rm-williams', 'koio'],
      situations: ['outdoor work', 'hiking', 'winter'],
      image: 'img/wardrobe/vidda-pro-2.jpg',
      washAfterWears: 7
    },
    {
      id: 'outlier-charcoal',
      name: 'Outlier Slim Dungarees',
      category: 'pants',
      subcategory: 'everyday',
      role: 'Everyday technical pant',
      colors: ['charcoal'],
      quantity: 1,
      status: 'to-buy',
      priority: 'spring',
      seasons: ['spring', 'summer', 'fall', 'winter'],
      formality: 'casual',
      tags: ['everyday', 'technical', 'town', 'travel'],
      pairsWithIds: ['grant-stone', 'koio', 'rancourt', 'ocbd-white', 'ocbd-blue', 'ocbd-chambray', 'merino-gray', 'merino-navy'],
      conflicts: [],
      situations: ['daily wear', 'town', 'travel'],
      image: 'img/wardrobe/outlier-charcoal.jpg',
      washAfterWears: 6
    },
    {
      id: 'outlier-navy',
      name: 'Outlier Slim Dungarees',
      category: 'pants',
      subcategory: 'everyday',
      role: 'Everyday technical pant',
      colors: ['navy'],
      quantity: 1,
      status: 'to-buy',
      priority: 'spring',
      seasons: ['spring', 'summer', 'fall', 'winter'],
      formality: 'casual',
      tags: ['everyday', 'technical', 'town', 'travel'],
      pairsWithIds: ['grant-stone', 'koio', 'rancourt', 'ocbd-white', 'ocbd-blue', 'ocbd-chambray', 'merino-gray', 'merino-rust'],
      conflicts: [],
      situations: ['daily wear', 'town', 'travel'],
      image: 'img/wardrobe/outlier-navy.jpg',
      washAfterWears: 6
    },
    {
      id: 'chinos-khaki',
      name: 'Proper Cloth Chinos',
      category: 'pants',
      subcategory: 'dress',
      role: 'Dress casual pant',
      colors: ['khaki'],
      quantity: 1,
      status: 'to-buy',
      priority: 'spring',
      seasons: ['spring', 'summer', 'fall'],
      formality: 'smart-casual',
      tags: ['dress', 'travel', 'town'],
      pairsWithIds: ['rm-williams', 'ocbd-white', 'ocbd-blue', 'ocbd-chambray'],
      conflicts: ['red-wing', 'schnees', 'muck-boot', 'salomon-hiking'],
      situations: ['dinner', 'events', 'travel'],
      image: 'img/wardrobe/chinos-khaki.jpg',
      washAfterWears: 4
    },
    {
      id: 'chinos-olive',
      name: 'Proper Cloth Chinos',
      category: 'pants',
      subcategory: 'dress',
      role: 'Dress casual pant',
      colors: ['olive'],
      quantity: 1,
      status: 'to-buy',
      priority: 'spring',
      seasons: ['spring', 'summer', 'fall'],
      formality: 'smart-casual',
      tags: ['dress', 'travel', 'town'],
      pairsWithIds: ['rm-williams', 'ocbd-white', 'ocbd-blue', 'ocbd-chambray'],
      conflicts: ['red-wing', 'schnees', 'muck-boot', 'salomon-hiking'],
      situations: ['dinner', 'events', 'travel'],
      image: 'img/wardrobe/chinos-olive.jpg',
      washAfterWears: 4
    },

    // === SHIRTS ===
    {
      id: 'filson-guide-1',
      name: 'Filson Alaskan Guide',
      category: 'shirts',
      subcategory: 'work',
      role: 'Work shirt',
      colors: ['rust'],
      quantity: 1,
      status: 'to-buy',
      priority: null,
      seasons: ['fall', 'winter', 'spring'],
      formality: 'rugged',
      tags: ['work', 'outdoor', 'rugged', 'warm'],
      pairsWithIds: ['vidda-pro-1', 'vidda-pro-2', 'red-wing'],
      conflicts: ['rm-williams', 'koio', 'rancourt', 'chinos-khaki', 'chinos-olive'],
      situations: ['outdoor work', 'cabin'],
      image: 'img/wardrobe/filson-guide-1.jpg',
      washAfterWears: 4
    },
    {
      id: 'filson-guide-2',
      name: 'Filson Alaskan Guide',
      category: 'shirts',
      subcategory: 'work',
      role: 'Work shirt',
      colors: ['olive'],
      quantity: 1,
      status: 'to-buy',
      priority: null,
      seasons: ['fall', 'winter', 'spring'],
      formality: 'rugged',
      tags: ['work', 'outdoor', 'rugged', 'warm'],
      pairsWithIds: ['vidda-pro-1', 'vidda-pro-2', 'red-wing'],
      conflicts: ['rm-williams', 'koio', 'rancourt', 'chinos-khaki', 'chinos-olive'],
      situations: ['outdoor work', 'cabin'],
      image: 'img/wardrobe/filson-guide-2.jpg',
      washAfterWears: 4
    },
    {
      id: 'ocbd-white',
      name: 'Gitman OCBD',
      category: 'shirts',
      subcategory: 'oxford',
      role: 'Universal shirt',
      colors: ['white'],
      quantity: 1,
      status: 'to-buy',
      priority: 'spring',
      seasons: ['spring', 'summer', 'fall', 'winter'],
      formality: 'smart-casual',
      tags: ['dress', 'everyday', 'travel', 'town', 'versatile'],
      pairsWithIds: ['rm-williams', 'grant-stone', 'chinos-khaki', 'chinos-olive', 'outlier-charcoal', 'outlier-navy'],
      conflicts: [],
      situations: ['daily wear', 'dinner', 'travel'],
      image: 'img/wardrobe/ocbd-white.jpg',
      washAfterWears: 2
    },
    {
      id: 'ocbd-blue',
      name: 'Gitman OCBD',
      category: 'shirts',
      subcategory: 'oxford',
      role: 'Universal shirt',
      colors: ['light blue'],
      quantity: 1,
      status: 'to-buy',
      priority: 'spring',
      seasons: ['spring', 'summer', 'fall', 'winter'],
      formality: 'smart-casual',
      tags: ['dress', 'everyday', 'travel', 'town', 'versatile'],
      pairsWithIds: ['rm-williams', 'grant-stone', 'chinos-khaki', 'chinos-olive', 'outlier-charcoal', 'outlier-navy'],
      conflicts: [],
      situations: ['daily wear', 'dinner', 'travel'],
      image: 'img/wardrobe/ocbd-blue.jpg',
      washAfterWears: 2
    },
    {
      id: 'ocbd-chambray',
      name: 'Gitman OCBD',
      category: 'shirts',
      subcategory: 'oxford',
      role: 'Universal shirt',
      colors: ['chambray'],
      quantity: 1,
      status: 'to-buy',
      priority: 'spring',
      seasons: ['spring', 'summer', 'fall', 'winter'],
      formality: 'smart-casual',
      tags: ['dress', 'everyday', 'travel', 'town', 'versatile'],
      pairsWithIds: ['rm-williams', 'grant-stone', 'chinos-khaki', 'chinos-olive', 'outlier-charcoal', 'outlier-navy'],
      conflicts: [],
      situations: ['daily wear', 'dinner', 'travel'],
      image: 'img/wardrobe/ocbd-chambray.jpg',
      washAfterWears: 2
    },
    {
      id: 'merino-gray',
      name: 'Icebreaker Merino Tee',
      category: 'shirts',
      subcategory: 'tee',
      role: 'Base layer / casual',
      colors: ['gray'],
      quantity: 1,
      status: 'to-buy',
      priority: 'spring',
      seasons: ['spring', 'summer', 'fall', 'winter'],
      formality: 'casual',
      tags: ['casual', 'base-layer', 'hiking', 'everyday'],
      pairsWithIds: ['salomon-hiking', 'grant-stone', 'outlier-charcoal', 'outlier-navy', 'vidda-pro-1', 'vidda-pro-2'],
      conflicts: [],
      situations: ['hiking', 'casual', 'layering'],
      image: 'img/wardrobe/merino-gray.jpg',
      washAfterWears: 3
    },
    {
      id: 'merino-navy',
      name: 'Icebreaker Merino Tee',
      category: 'shirts',
      subcategory: 'tee',
      role: 'Base layer / casual',
      colors: ['navy'],
      quantity: 1,
      status: 'to-buy',
      priority: 'spring',
      seasons: ['spring', 'summer', 'fall', 'winter'],
      formality: 'casual',
      tags: ['casual', 'base-layer', 'hiking', 'everyday'],
      pairsWithIds: ['salomon-hiking', 'grant-stone', 'outlier-charcoal', 'vidda-pro-1', 'vidda-pro-2'],
      conflicts: [],
      situations: ['hiking', 'casual', 'layering'],
      image: 'img/wardrobe/merino-navy.jpg',
      washAfterWears: 3
    },
    {
      id: 'merino-rust',
      name: 'Icebreaker Merino Tee',
      category: 'shirts',
      subcategory: 'tee',
      role: 'Base layer / casual',
      colors: ['rust'],
      quantity: 1,
      status: 'to-buy',
      priority: 'spring',
      seasons: ['spring', 'summer', 'fall', 'winter'],
      formality: 'casual',
      tags: ['casual', 'base-layer', 'hiking', 'everyday'],
      pairsWithIds: ['salomon-hiking', 'grant-stone', 'outlier-navy', 'vidda-pro-1', 'vidda-pro-2'],
      conflicts: [],
      situations: ['hiking', 'casual', 'layering'],
      image: 'img/wardrobe/merino-rust.jpg',
      washAfterWears: 3
    },
    {
      id: 'polo-navy',
      name: 'Sunspel Riviera Polo',
      category: 'shirts',
      subcategory: 'polo',
      role: 'Summer smart casual',
      colors: ['navy'],
      quantity: 1,
      status: 'to-buy',
      priority: 'summer',
      seasons: ['spring', 'summer'],
      formality: 'smart-casual',
      tags: ['summer', 'smart-casual', 'travel', 'town'],
      pairsWithIds: ['koio', 'outlier-charcoal', 'chinos-khaki'],
      conflicts: ['red-wing', 'schnees', 'muck-boot'],
      situations: ['travel', 'town', 'warm weather'],
      image: 'img/wardrobe/polo-navy.jpg',
      washAfterWears: 2
    },
    {
      id: 'polo-sage',
      name: 'Sunspel Riviera Polo',
      category: 'shirts',
      subcategory: 'polo',
      role: 'Summer smart casual',
      colors: ['sage'],
      quantity: 1,
      status: 'to-buy',
      priority: 'summer',
      seasons: ['spring', 'summer'],
      formality: 'smart-casual',
      tags: ['summer', 'smart-casual', 'travel', 'town'],
      pairsWithIds: ['koio', 'outlier-charcoal', 'outlier-navy', 'chinos-khaki'],
      conflicts: ['red-wing', 'schnees', 'muck-boot'],
      situations: ['travel', 'town', 'warm weather'],
      image: 'img/wardrobe/polo-sage.jpg',
      washAfterWears: 2
    },
    {
      id: 'filson-flannel',
      name: 'Filson Heavy Flannel',
      category: 'shirts',
      subcategory: 'flannel',
      role: 'Cold weather shirt',
      colors: ['burgundy'],
      quantity: 1,
      status: 'to-buy',
      priority: null,
      seasons: ['fall', 'winter'],
      formality: 'rugged',
      tags: ['warm', 'outdoor', 'rugged', 'cold'],
      pairsWithIds: ['vidda-pro-1', 'vidda-pro-2', 'red-wing'],
      conflicts: ['rm-williams', 'koio', 'chinos-khaki'],
      situations: ['cold weather', 'cabin', 'outdoor work'],
      image: 'img/wardrobe/filson-flannel.png',
      washAfterWears: 5
    },

    // === OUTERWEAR ===
    {
      id: 'mackinaw',
      name: 'Filson Mackinaw Cruiser',
      category: 'outerwear',
      subcategory: 'jacket',
      role: 'Heavy wool jacket',
      colors: ['forest green'],
      quantity: 1,
      status: 'owned',
      priority: null,
      seasons: ['fall', 'winter'],
      formality: 'rugged',
      tags: ['warm', 'outdoor', 'rugged', 'cold', 'winter'],
      pairsWithIds: ['vidda-pro-1', 'vidda-pro-2', 'schnees', 'red-wing'],
      conflicts: ['koio', 'polo-navy', 'polo-sage'],
      situations: ['fall', 'winter', 'outdoor work'],
      image: 'img/wardrobe/mackinaw.jpg',
      washAfterWears: null
    },
    {
      id: 'softshell',
      name: 'Lululemon Softshell',
      category: 'outerwear',
      subcategory: 'jacket',
      role: 'Spring / fall midlayer',
      colors: ['charcoal'],
      quantity: 1,
      status: 'to-buy',
      priority: 'spring',
      seasons: ['spring', 'fall'],
      formality: 'casual',
      tags: ['midlayer', 'versatile', 'travel', 'town'],
      pairsWithIds: ['grant-stone', 'outlier-charcoal', 'outlier-navy', 'ocbd-white', 'ocbd-blue', 'merino-gray', 'merino-navy'],
      conflicts: [],
      situations: ['spring', 'fall', 'travel'],
      image: 'img/wardrobe/softshell.jpg',
      washAfterWears: null
    },

    // === ACCESSORIES ===
    {
      id: 'hanks-belt',
      name: 'Hanks Leather Belt',
      category: 'accessories',
      subcategory: 'belt',
      role: 'Everyday belt',
      colors: ['brown'],
      quantity: 1,
      status: 'to-buy',
      priority: 'spring',
      seasons: ['spring', 'summer', 'fall', 'winter'],
      formality: 'casual',
      tags: ['everyday', 'leather'],
      pairsWithIds: [],
      conflicts: [],
      situations: ['daily wear'],
      image: 'img/wardrobe/hanks-belt.jpg',
      washAfterWears: null
    },
    {
      id: 'fox-river-socks',
      name: 'Fox River Merino Socks',
      category: 'accessories',
      subcategory: 'socks',
      role: 'Everyday socks',
      colors: ['gray'],
      quantity: 1,
      status: 'to-buy',
      priority: 'spring',
      seasons: ['spring', 'summer', 'fall', 'winter'],
      formality: 'casual',
      tags: ['everyday', 'merino'],
      pairsWithIds: [],
      conflicts: [],
      situations: ['daily wear'],
      image: 'img/wardrobe/fox-river-socks.jpg',
      washAfterWears: null
    },
    {
      id: 'hestra-gloves',
      name: 'Hestra Leather Gloves',
      category: 'accessories',
      subcategory: 'gloves',
      role: 'Winter gloves',
      colors: ['brown'],
      quantity: 1,
      status: 'to-buy',
      priority: null,
      seasons: ['fall', 'winter'],
      formality: 'casual',
      tags: ['winter', 'cold'],
      pairsWithIds: [],
      conflicts: [],
      situations: ['winter'],
      image: 'img/wardrobe/hestra-gloves.png',
      washAfterWears: null
    },
    {
      id: 'rayban-aviator',
      name: 'Ray-Ban Aviator',
      category: 'accessories',
      subcategory: 'sunglasses',
      role: 'Sunglasses',
      colors: ['gold'],
      quantity: 1,
      status: 'to-buy',
      priority: 'spring',
      seasons: ['spring', 'summer', 'fall', 'winter'],
      formality: 'casual',
      tags: ['everyday'],
      pairsWithIds: [],
      conflicts: [],
      situations: ['daily wear', 'outdoor'],
      image: 'img/wardrobe/rayban-aviator.jpg',
      washAfterWears: null
    },
    {
      id: 'filson-cap',
      name: 'Filson Wool Cap',
      category: 'accessories',
      subcategory: 'hat',
      role: 'Winter cap',
      colors: ['charcoal'],
      quantity: 1,
      status: 'to-buy',
      priority: null,
      seasons: ['fall', 'winter'],
      formality: 'casual',
      tags: ['winter', 'cold'],
      pairsWithIds: [],
      conflicts: [],
      situations: ['winter', 'cold'],
      image: 'img/wardrobe/filson-cap.jpg',
      washAfterWears: null
    },
    {
      id: 'saddleback-wallet',
      name: 'Saddleback Wallet',
      category: 'accessories',
      subcategory: 'wallet',
      role: 'Wallet',
      colors: ['chestnut'],
      quantity: 1,
      status: 'to-buy',
      priority: null,
      seasons: ['spring', 'summer', 'fall', 'winter'],
      formality: 'casual',
      tags: ['everyday'],
      pairsWithIds: [],
      conflicts: [],
      situations: ['daily wear'],
      image: 'img/wardrobe/saddleback-wallet.jpg',
      washAfterWears: null
    },
    {
      id: 'filson-briefcase',
      name: 'Filson Briefcase',
      category: 'accessories',
      subcategory: 'bag',
      role: 'Work bag',
      colors: ['tan'],
      quantity: 1,
      status: 'to-buy',
      priority: null,
      seasons: ['spring', 'summer', 'fall', 'winter'],
      formality: 'smart-casual',
      tags: ['work', 'travel'],
      pairsWithIds: [],
      conflicts: [],
      situations: ['work', 'travel'],
      image: 'img/wardrobe/filson-briefcase.jpg',
      washAfterWears: null
    }
  ],

  outfits: [
    {
      id: 'work-outdoor',
      name: 'Work / Outdoor',
      itemIds: ['red-wing', 'vidda-pro-1', 'filson-flannel'],
      seasons: ['fall', 'winter', 'spring'],
      weatherRange: { minTemp: 10, maxTemp: 50 }
    },
    {
      id: 'everyday-town',
      name: 'Everyday / Town',
      itemIds: ['grant-stone', 'outlier-charcoal', 'ocbd-white'],
      seasons: ['spring', 'fall', 'winter'],
      weatherRange: { minTemp: 25, maxTemp: 65 }
    },
    {
      id: 'smart-casual',
      name: 'Smart Casual',
      itemIds: ['rm-williams', 'chinos-khaki', 'ocbd-blue'],
      seasons: ['spring', 'summer', 'fall'],
      weatherRange: { minTemp: 40, maxTemp: 80 }
    },
    {
      id: 'summer-casual',
      name: 'Summer Casual',
      itemIds: ['koio', 'outlier-navy', 'polo-navy'],
      seasons: ['spring', 'summer'],
      weatherRange: { minTemp: 60, maxTemp: 95 }
    },
    {
      id: 'hiking',
      name: 'Hiking',
      itemIds: ['salomon-hiking', 'vidda-pro-1', 'merino-gray'],
      seasons: ['spring', 'summer', 'fall'],
      weatherRange: { minTemp: 30, maxTemp: 80 }
    },
    {
      id: 'winter',
      name: 'Winter',
      itemIds: ['schnees', 'vidda-pro-2', 'mackinaw'],
      seasons: ['winter'],
      weatherRange: { minTemp: -30, maxTemp: 25 }
    }
  ]
};
